# 自定义构建配置文件示例
# ******************************************
# build: 构建参数（通用配置）
#   name: 当前构建的标识(仅用于区分不同构建配置)
#   type: 构建类型, 指定为HiveNetMicro
#   source: str, 构建源文件目录, 为当前构建配置文件所在目录的相对目录
#   output: str, 构建结果输出目录, 为当前构建配置文件所在目录的相对目录
#   successTips: list, 构建成功后的提示内容, 按行显示列表内容
# ******************************************
build:
  name: 'demo'
  type: SeflBuildTool
  source: ~
  output: "../build"
  successTips:
    - "成功构建"
    - "提示信息"

# ******************************************
# dirs: 要创建的文件夹(自定义配置，使用公共的ProcesserBuildDir插件)
# Item Key: 要在输出目录下创建的文件夹, 支持使用"/"创建多级文件夹
#   clear: bool, 文件夹已存在的情况是否清空目录, 默认为false
#   copy: list, 复制的文件或目录清单, 每项为一个复制操作, 支持以下两种配置方式
#     src_file: str, 直接传入要复制文件的路径(为源文件目录的相对目录), 直接复制到当前配置文件夹的根目录下
#     ["src_file", "dest_file"]: list, 第1个参数为要复制的文件路径, 第2个参数为要保存的文件路径(当前配置文件夹的相对路径)
#   copyAll: list, 要复制所有子文件及子文件夹的目录清单，每项为一个复制操作，支持以下两种配置方式
#     src_dir: str, 直接传入要复制的文件夹(为源文件目录的相对目录), 直接将该文件夹的所有子文件和子目录复制到当前配置文件夹的根目录下
#     ["src_dir", "dest_dir"]: list, 第1个参数为要复制文件夹, 第2个参数为要保存的文件夹(当前配置文件夹的相对路径)
# ******************************************
dirs:
  config:
    clear: true  # 自动创建config目录

# ******************************************
# getSysInfos: 要获取并放置到管道上下文的配置
#   Item Key: 获取信息唯一标识(自定义)
#     infoType: str, 信息类型标识（extend_para.yaml中ProcesserGetSysInfos下的信息类型）
#       注: 如果不设置代表使用Item Key作为信息类型标识
#     getKey: str, 自定义写入上下文的信息获取key, 如果不设置则使用extend_para.yaml中对应信息类型的默认值
#     args: list, 调用获取信息函数的固定位置入参, 根据实际extend_para.yaml中对应信息类型的获取函数要求传参
#     kwargs: dict, 调用获取信息函数的key-value入参, 根据实际extend_para.yaml中对应信息类型的获取函数要求传参
# ******************************************
getSysInfos:
  platform:
  Home:
    infoType: sysEnviron
    getKey: Home
    args:
      - HOME
    kwargs:
      default: '/?'

# ******************************************
# prompt: 获取交互输入
# ******************************************
prompt:
  -
    promptType: radio
    values:
      - ["val1", "text1"]
      - ["val2", "text2"]
    default: "val2"
    setValuePath: "prompt/radio"
  -
    engine: PromptPlus
    text: "input you word: "
    default: "no"
    setValuePath: "prompt/input"

# ******************************************
# print: 要打印的上下文信息
#   Item Key: 打印步骤唯一标识
#     showTips: str, 打印内容前的提示信息, 选填
#     path: str, 要打印的上下文字典检索路径
#       注1: 从根目录开始搜索, 路径下多个key之间使用'/'分隔, 例如 'root/key1/key2'
#       注2: 可以通过[索引值]搜索特定key下第几个配置(数组或字典), 例如 'root/key1[0]'搜素key1下第一个对象
#     default: Any, 路径找不到时打印的默认值
#     jsonPrint: bool, 使用json方式打印(格式化后的显示), 默认为True
# ******************************************
print:
  sysPrint:
    showTips: 系统信息
    path: sysInfos/platform
  envPrint:
    showTips: 环境变量
    path: sysInfos/Home
  contextPrint:
    showTips: 输入结果
    path: prompt

# ******************************************
# 自定义构建插件处理配置
# ******************************************
demoKey:
  testKey:
    - "show a"
