# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: msg_json.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0emsg_json.proto\x12\x0bHiveNetGRPC\"5\n\nRpcRequest\x12\x11\n\tpara_json\x18\x01 \x01(\t\x12\x14\n\x0c\x65xtend_bytes\x18\x02 \x01(\x0c\"\x88\x01\n\x0bRpcResponse\x12\x13\n\x0breturn_json\x18\x01 \x01(\t\x12\x14\n\x0c\x65xtend_bytes\x18\x02 \x01(\x0c\x12\x11\n\tcall_code\x18\x03 \x01(\t\x12\x10\n\x08\x63\x61ll_msg\x18\x04 \x01(\t\x12\x12\n\ncall_error\x18\x05 \x01(\t\x12\x15\n\rcall_msg_para\x18\x06 \x01(\t\" \n\rHealthRequest\x12\x0f\n\x07service\x18\x01 \x01(\t\"\x9c\x01\n\x0eHealthResponse\x12\x39\n\x06status\x18\x01 \x01(\x0e\x32).HiveNetGRPC.HealthResponse.ServingStatus\"O\n\rServingStatus\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0b\n\x07SERVING\x10\x01\x12\x0f\n\x0bNOT_SERVING\x10\x02\x12\x13\n\x0fSERVICE_UNKNOWN\x10\x03\x32\xa4\x03\n\x0bJsonService\x12\x45\n\x0eGRpcCallSimple\x12\x17.HiveNetGRPC.RpcRequest\x1a\x18.HiveNetGRPC.RpcResponse\"\x00\x12Q\n\x18GRpcCallClientSideStream\x12\x17.HiveNetGRPC.RpcRequest\x1a\x18.HiveNetGRPC.RpcResponse\"\x00(\x01\x12Q\n\x18GRpcCallServerSideStream\x12\x17.HiveNetGRPC.RpcRequest\x1a\x18.HiveNetGRPC.RpcResponse\"\x00\x30\x01\x12V\n\x1bGRpcCallBidirectionalStream\x12\x17.HiveNetGRPC.RpcRequest\x1a\x18.HiveNetGRPC.RpcResponse\"\x00(\x01\x30\x01\x12P\n\x13GRpcCallHealthCheck\x12\x1a.HiveNetGRPC.HealthRequest\x1a\x1b.HiveNetGRPC.HealthResponse\"\x00\x62\x06proto3')



_RPCREQUEST = DESCRIPTOR.message_types_by_name['RpcRequest']
_RPCRESPONSE = DESCRIPTOR.message_types_by_name['RpcResponse']
_HEALTHREQUEST = DESCRIPTOR.message_types_by_name['HealthRequest']
_HEALTHRESPONSE = DESCRIPTOR.message_types_by_name['HealthResponse']
_HEALTHRESPONSE_SERVINGSTATUS = _HEALTHRESPONSE.enum_types_by_name['ServingStatus']
RpcRequest = _reflection.GeneratedProtocolMessageType('RpcRequest', (_message.Message,), {
  'DESCRIPTOR' : _RPCREQUEST,
  '__module__' : 'msg_json_pb2'
  # @@protoc_insertion_point(class_scope:HiveNetGRPC.RpcRequest)
  })
_sym_db.RegisterMessage(RpcRequest)

RpcResponse = _reflection.GeneratedProtocolMessageType('RpcResponse', (_message.Message,), {
  'DESCRIPTOR' : _RPCRESPONSE,
  '__module__' : 'msg_json_pb2'
  # @@protoc_insertion_point(class_scope:HiveNetGRPC.RpcResponse)
  })
_sym_db.RegisterMessage(RpcResponse)

HealthRequest = _reflection.GeneratedProtocolMessageType('HealthRequest', (_message.Message,), {
  'DESCRIPTOR' : _HEALTHREQUEST,
  '__module__' : 'msg_json_pb2'
  # @@protoc_insertion_point(class_scope:HiveNetGRPC.HealthRequest)
  })
_sym_db.RegisterMessage(HealthRequest)

HealthResponse = _reflection.GeneratedProtocolMessageType('HealthResponse', (_message.Message,), {
  'DESCRIPTOR' : _HEALTHRESPONSE,
  '__module__' : 'msg_json_pb2'
  # @@protoc_insertion_point(class_scope:HiveNetGRPC.HealthResponse)
  })
_sym_db.RegisterMessage(HealthResponse)

_JSONSERVICE = DESCRIPTOR.services_by_name['JsonService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _RPCREQUEST._serialized_start=31
  _RPCREQUEST._serialized_end=84
  _RPCRESPONSE._serialized_start=87
  _RPCRESPONSE._serialized_end=223
  _HEALTHREQUEST._serialized_start=225
  _HEALTHREQUEST._serialized_end=257
  _HEALTHRESPONSE._serialized_start=260
  _HEALTHRESPONSE._serialized_end=416
  _HEALTHRESPONSE_SERVINGSTATUS._serialized_start=337
  _HEALTHRESPONSE_SERVINGSTATUS._serialized_end=416
  _JSONSERVICE._serialized_start=419
  _JSONSERVICE._serialized_end=839
# @@protoc_insertion_point(module_scope)
