# ******************************************
# 构建工具配置
# Item Key: 构建类型标识(type)
#   plugins: str|list, 该构建类型的自有管道插件目录(构建工具目录的相对路径)
#     注: 如果为str代表指定1个路径, 如果是list则通过数组形式指定多个管道插件目录
#   pipeline: str, 构建管道配置文件(构建工具目录的相对路径)
#   selfConfig: dict, 不同类型构建工具的自有配置参数
# ******************************************
SeflBuildTool:
  plugins: plugins
  pipeline: build_pipeline.yaml
  selfConfig: